theme: jekyll-theme-slate
title: Angular Tags Dropdown
description: AngularJS component to manage tags in input with dropdown selector based on Bootstrap-UI

show_downloads: true
google_analytics: UA-98305945-1